# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0f80f529acf3f64519aa4cecd9904e5b58d1b6f6c0ed67b1f159c9980a7f0c62437e1935df9a6cd2912fdb0793adbf40fb28d28d9fc67e0e2317965d55f7184

test:
  secret_key_base: 259744489a731247f03c2106322fdaf7ed7568c66d684da5da8cc1c14361b282bfdde4849effbe5c60a4541a6494cafe93f457f3cd26451442403a159444cd23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
